spring:
  cloud:
    gateway:
      routes:
        #第三方oss服务等
        - id: third-part_route
          uri: lb://ThirdPartApp
          predicates:
            - Path=/api/third-part/**
          #去除api前缀
          filters:
            - RewritePath=/api/third-part/?(?<segment>.*), /$\{segment}

        #产品服务
        - id: product_route
          uri: lb://productApp
          predicates:
            - Path=/api/product/**
          #去除api前缀
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        #会员服务
        - id: member_route
          uri: lb://memberApp
          predicates:
            - Path=/api/member/**
          #去除api前缀
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        #后台管理服务
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

