spring:
  cloud:
    gateway:
      routes:
        - id: third-part_route
          uri: lb://ThirdPartApp
          predicates:
            - Path=/api/third-part/**
          #去除api前缀
          filters:
            - RewritePath=/api/third-part/?(?<segment>.*), /$\{segment}

        - id: product_route
          uri: lb://productApp
          predicates:
            - Path=/api/product/**
          #去除api前缀
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

